from .coco import COCO
from .voc import VOC
from .ade20k import ADE20K
from .cityscapes import CityScapes
from .cityscapes_rgbd import CityScapesRGBD
from .cityscapes2c import CityScapes2c
from .cityscapes2c_weighted import CityScapes2cWeighted
from .cityscapes_rgbd_19c import CityScapesRGBD19c
from .lowwire_rgbflow import LowWiresRGBFlow
from .lowwire import LowWires